[project]
name = "langgraph-to-temporal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=1.0.4",
    "claude-agent-sdk",
]
